# fly.toml app configuration file generated for full-stack-open-pokedex-p11 on 2025-01-26T18:55:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-p11'
primary_region = 'otp'

[env]
  PORT = "3000"

[processes]
  app = "node app.js" 

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
