name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  COMMIT_MSG_CONTAINS_SKIP: ${{ contains(join(github.event.commits.*.message, ' '), '#skip') }}

jobs:
  set_env_in_job_output:
    runs-on: ubuntu-20.04
    outputs:
      skip: ${{ steps.init.outputs.skip }}
    steps:
      - name: Extract env variable and set it in job output
        id: init
        run: |
          echo "skip=${{ env.COMMIT_MSG_CONTAINS_SKIP }}" >> $GITHUB_OUTPUT
  simple_deployment_pipeline:
    needs: [set_env_in_job_output]
    runs-on: ubuntu-20.04
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: unit tests
        run: npm run test
      - name: e2e tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: deploy to fly.io
        if: ${{ github.event_name == 'push' && needs.set_env_in_job_output.outputs.skip == 'false' }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  tag_release:
    needs: [simple_deployment_pipeline, set_env_in_job_output]
    runs-on: ubuntu-20.04
    if: ${{ needs.set_env_in_job_output.outputs.skip == 'false' }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
