name: Test Notifications

on:
  push:
    branches:
      - test-notify
  pull_request:
    branches: [test-notify]
    types: [opened, synchronize]

# rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112

jobs:
  notify:
    runs-on: ubuntu-20.04
    steps:
      - name: output SHA
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: echo "$COMMIT_SHA"

      - name: The job succeeded
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: ${{ success() }}
        with:
          severity: info
          details: Test Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: The job failed
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: ${{ failure() }}
        with:
          severity: error
          details: Test Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
