name: Test Notifications

on:
  push:
    branches:
      - test-notify
  pull_request:
    branches: [test-notify]
    types: [opened, synchronize]

# rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112

jobs:
  notify:
    runs-on: ubuntu-20.04
    steps:
      - name: output SHA
        env:
          COMMIT_SHA: ${{ github.sha }}
        #run: echo "$COMMIT_SHA"
        run: exit 1
      - name: The job succeeded
        uses: sarisia/actions-status-discord@5ddd3b114a98457dd80a39b2f00b6a998cd69008
        if: ${{ success() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          content: 'A new version of Pokedex deployed'
          title: 'Status: ${{ job.status }}'
          description: |
            by `${{ github.actor }}`
            Click [here](https://full-stack-open-pokedex-p11.fly.dev) to visit the deployed app!
          username: GitHub Actions
      - name: The job failed
        uses: sarisia/actions-status-discord@5ddd3b114a98457dd80a39b2f00b6a998cd69008
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: 'Deployment failed'
          title: 'Status: ${{ job.status }}'
          description: 'commit [${{ github.sha }}](https://github.com/${{ github.repository/commit/${{ github.sha }} }}) by `${{ github.actor }}` broke the build'
          username: GitHub Actions
